### ISSUE TITLE
nav bar

### ISSUE THREAD

**Issue by remipichon** [assomaker/manifmaker#156]
Chrome Developers (@ChromiumDev) tweeted at 11:58 AM on Sat, Apr 30, 2016:
Did you miss @aerotwist & @DasSurma build a Side Nav live?? Fear not! Watch here: https://t.co/FX9aoQkKG7 https://t.co/wYCK9s2ERL
(https://twitter.com/ChromiumDev/status/726365136961806336?s=03)

**Comment by PtiLuky** [comment]
Il y a du fonctionnel/design à revoir à propos de la sidebar ?
(à part p-e une image de profil à personnaliser, mais ça serait pour plus tard je présume)

**Comment by remipichon** [comment]
Tu as tout à fait raison. 

Nous verrons l'image de user lorsque sera abordé la création d'utilisateur
