### ISSUE TITLE
/trump

### ISSUE THREAD

**Issue by remipichon** [assomaker/manifmaker#279]
mettre une redirection vers le plugin chrome make donald drumpf again

**Comment by martinezleoml** [comment]
Mdrrrrrr :')

**Comment by ghost** [comment]
T'es un génie 😆

**Comment by remipichon** [comment]
Ha, mais vous lisez mes issues ?

**Comment by ghost** [comment]
Oui. Rarement jusqu'au bout parce que je comprends pas tout le temps 😆  Mais si tu me poses une question j'essaie d'y répondre si je la vois 😄

**Comment by remipichon** [comment]
Tu peux changer les options de notifications pour ne recevoir des mails que
lorsqu'il est fait mention de toi (avec @cpalier)
