### ISSUE TITLE
page login/register et conf-maker

### ISSUE THREAD

**Issue by remipichon** [assomaker/manifmaker#285]
pages 
* /register
* /login
* /conf-maker
* /task

Le contenu des pages en question ne s'affiche que sur une petite colonne, @PtiLuky peux tu rétablir l'affichage d'avant ?

**Comment by remipichon** [comment]
@PtiLuky as tu progressé sur le sujet ?

**Comment by PtiLuky** [comment]
Non, je suis désolé, mon météor ne se relance pas.
Du coup direction nouveau cloning du dossier du git, mais je vais difficilement pouvoir m'en charger avant jeudi...

**Comment by remipichon** [comment]
Dammit, je comprend pas.

Dis moi si tu as d'autres difficultés.




--
Remi Pichon


2016-12-05 18:50 GMT+01:00 PtiLuky <notifications@github.com>:

**Comment by PtiLuky** [comment]
https://github.com/assomaker/manifmaker/commit/f7b4d6ad3bc5da7c45c802061d9466f1bcdec59d

Normalement c'est fixé, j'ai vérifié les autres pages, il me semble pas que ça ait cassé autre chose !
