### ISSUE TITLE
assignment : worflow des collapsde/expand de task et user list

### ISSUE THREAD

**Issue by remipichon** [assomaker/manifmaker#300]
* ~~est-ce qu’on peut compléter le populate-data pour avoir une tâche qu’on peut affecter à un user qui est validé et qui est dispo sur le timeslot correspondant à la tâche, stp?~~
* ~~le calendar term n'est pas le bon lorsqu'on arrive sur la page (task, assignment, user), du coup les actions marchent mal lorsqu'on select un timeslot, une task....~~
* en mode TaskToUser, dès qu’on sélectionne une tâche, la liste de tâche se rétracte au profit de la userList. C’est assez chiant. est-ce qu’on peut garder ce principe (parce qu’il est intéressant) mais le déplacer une fois qu’on a sélectionné un timeslot?

**Comment by remipichon** [comment]
## le calendar term n'est pas le bon lorsqu'on arrive sur la page (task, assignment, user), du coup les actions marchent mal lorsqu'on select un timeslot, une task.... ==> 🆗 

le calendrier reste selectionné avec le précédent, mais la selecteur remet toujours le premier de la liste

~~task : le default time pour la creation de timeslot reprend le precedent selected term, 👍~~
assignment : la filtre des tasks ne reprend pas le derniere selected term, idem pour user👎
 user2 sur term1 ou term3
task1 sur term2 

~~term select : ne reprend jamais le derniere selected term 👎 ~~

**Comment by ghost** [comment]
Je crois que c'est à peu près tout ce que je t'ai reporté pour l'instant.

**Comment by remipichon** [comment]
Je corrige tout ca, je deploie et tu pourras me dire si ca va

**Comment by remipichon** [comment]
## en mode TaskToUser, dès qu’on sélectionne une tâche, la liste de tâche se rétracte au profit de la userList. C’est assez chiant. est-ce qu’on peut garder ce principe (parce qu’il est intéressant) mais le déplacer une fois qu’on a sélectionné un timeslot?

@cpalliere 

actuellement le workflow pour taskToUser est le suivant  : 
* click "userToTask"
  * userList collapses with no users displayed
  * taskList expands with all tasks displayed
* click on a task name
  * userList expands with still no users displayed
  * taskList collapses with still all tasks displayed
* click on a timeslot
  * open people need popover
* click on a people need
  * userList remains expanded with assignable users displayed
  * taskList remains collapsed with still all tasks displayed


toi tu veux
* click "userToTask"
  * userList collapses with no users displayed
  * taskList expands with all tasks displayed
* click on a task name
  * userList _remains collapsed_ with still no users displayed
  * taskList _remain expanded_ with still all tasks displayed
* click on a timeslot
  * open people need popover
* click on a people need
  * userList _expands_ with assignable users displayed
  * taskList _collapses_ with still all tasks displayed

C'est ca ?

**Comment by remipichon** [comment]
## est-ce qu’on peut compléter le populate-data pour avoir une tâche qu’on peut affecter à un user qui est validé et qui est dispo sur le timeslot correspondant à la tâche, stp?

@cpalliere 

tu as la tache "collage parcours 1" auquel tu peux affecter le user "Sticky Expert" sur 3 créneaux : 
* 17/04 de 6h à 8h
* 18/04 de 6h à 8h
* 30/04 de 6h à 8h

/inject-data pour tout reinjecter

**Comment by ghost** [comment]
C'est exactement ça.
