### ISSUE TITLE
user availabilities - term select

### ISSUE THREAD

**Issue by remipichon** [assomaker/manifmaker#305]
Ne pas faire de liste deroulante pour les différentes plage horaire. Un user ne voyant pas ça ne selectionnera des créneaux que dans les plages horaires affichés par defaut. Faire une liste mais non deroulante.

=> 
en mode milestone, avec tous les assignments terms sous forme de boutons au dessus du calendrier (afficher egalement la deadline d'ajout de dispo)

**Comment by PtiLuky** [comment]
Pour useravailibilities (et le reste), je me fais une nouvelle branche, à partir du master ou de celle que j'ai pour le planning ?

(sinon au niveau des merges je gère pas ça bien encore ^^ )

**Comment by remipichon** [comment]
Fais une nouvelle branche à partir de la dernière version de la Master.

Pas de soucis pour les merge, dans le doute, ne pousse pas sur Master pour
pas la casser :)

**Comment by PtiLuky** [comment]
Du coup on est d'accord que ça doit fonctionner : 
- une liste déjà déroulée au lieu d'une liste déroulante et toujours juste un calendrier en dessus
(- ou un calendrier par plage qui s'affichent tous en dessous ?)


"=>
en mode milestone, avec tous les assignments terms sous forme de boutons au dessus du calendrier (afficher egalement la deadline d'ajout de dispo)"
J'ai pas compris cette partie

**Comment by PtiLuky** [comment]
Sur le commit https://github.com/assomaker/manifmaker/commit/40bb31c0f37a66acf1bc95c907aa48ae2ea12b64 j'ai considéré la première option, la 2ème risquant de faire des pages à rallonge nan ?

(et le commit suivant c'est parce que j'avais réglé à "false" ce nouvel affichage... donc une correction pour mettre "true" et donc utiliser le nouvel affichage)

**Comment by remipichon** [comment]
C'était pas tres clair effectivement. Il s'agit de ne plus utiliser une
liste, déroulante ou pas. Afin que les différents terms soient visibles et
agréable à utiliser nous avons proposer d'afficher l'ensemble des terms
sous formes de labels/bouttons cliquable.

Un peu comme le nouveau Google Image, les terms sont affichés cote à cote
(disons en col-md-4

Un peu comme ca
https://docs.google.com/drawings/d/177RSxGhCrfp0bSZ4sj78n7cqQIzzNhxfXVzDIISCwkA/edit
Qu'en dis tu ?




--
Remi Pichon

**Comment by PtiLuky** [comment]
Okay je vois

Donc je fais un nouveau component et pas juste une modification du component AssignmentTermSelect ?

**Comment by remipichon** [comment]
Tu peux faire un nouveau component c'est une bonne idée.

AssignmentTermSelect doit rester une liste pour tous les autres cas (Task,
Assignment) ou une liste déroulante suffit




--
Remi Pichon


2017-01-18 12:47 GMT+01:00 PtiLuky <notifications@github.com>:

**Comment by PtiLuky** [comment]
Bien, du coup j'ai refait un affichage à base de boutons (4 par lignes) à la place de la liste déroulante à partir de la meme base que pour la liste déroulante ! https://github.com/assomaker/manifmaker/commit/efbcf1525cfe238ca45f909c08007bcfd1db390e

**Comment by PtiLuky** [comment]
Et le petit commit qui suit pour afficher la deadline.
(j'ai honte, j'ai galéré 30 min parce que j'avais oublié les règles des ReactivesVars :) )

**Comment by remipichon** [comment]
T'es au top ! C'est parfait !
