### ISSUE TITLE
Let's give a second chance to this project

### ISSUE THREAD

**Issue by remipichon** [assomaker/manifmaker#407]
* ~~build deploy to preproduction via VOC~~
  * ~~from scratch (db init user)~~
  * ~~update (without updating version)~~
* ~~configure Google/Facebook Authent on preprod (automate this via env) ==> just to test~~
* create framework for the guided tour (Activity + validation, Task + validation, User + availabilities + validation, Assignment back and forth, Export Agenda, Conf Maker (Sponge Bob story) ==> to design
* talk about it to 24H and Karna

**Comment by remipichon** [comment]
# install from scratch
* configure database with technical users (build time)
* configure export PDF stuff to work with compose 3

**Comment by LeoMouyna** [comment]
Are you kidding ?
I'm in if needed during summer !

**Comment by remipichon** [comment]
@LeoMouyna, ho cool, est ce que tu connais bien NodeJs ou ES6 ?

**Comment by LeoMouyna** [comment]
@remipichon Bien c'est vite dit, disons que je me débrouille avec. Il faut que je me remémore la manière dont tu as structuré le code et les principes de dev que tu as mis en place. Un domaine particulier à regarder ?

**Comment by remipichon** [comment]
@LeoMouyna 
@PtiLuky 

Un tour guidé est en place 
[http://tour-manifmaker.remip.eu/tour](http://tour-manifmaker.remip.eu/tour)
* le tour guidé ne passe par l'affectation 
* impossible de se connecter avec son Google ou Facebook, utiliser preprod pour tester les features à la main 

Une instance est en place 
[http://preprod-manifmaker.remip.eu/conf-maker](http://preprod-manifmaker.remip.eu/conf-maker)
* Facebook et Google authent fonctionne, à la premiere connexion, le user est ajouté à la team 'hard' avec tous les roles existants (= accès à toutes les features)
* l'export PDF n'est pas installé mais est implémenté


@LeoMouyna Peux tu t'amuser avec ces deux instances et les faire tourner à l'actuel bureau pour qu'ils puissent decider s'ils veulent partir avec pour la prochaine édition ?

@LeoMouyna Ne te prends pas la tete avec NodeJs ou MeteorJs, il faut d'abord une vraie équipe de Dev' pour reprendre le projet (je peux assurer le Ops).

**Comment by LeoMouyna** [comment]
@remipichon Petit probleme avec le tour guide, la console me sort en boucle waiting for .at-pwd-form mais rien ne s'affiche sur la page.
Concernant les user sur preprod, ce sont ceux qui sont dans inject data du serveur method ?

Est-ce qu'on a un backlog de ce qui est fait et de ce qu'il reste a faire pour que le projet soit iso assomaker ?

**Comment by remipichon** [comment]
@LeoMouyna weird, je viens d'arriver à lancer le tour, est ce qu'il plante en plein milieu ou juste au début ? (dans le doute, utilise Chrome desktop)
Lorsque les data sont en train d'être injecter, ne fait rien sur l'UI.

Pour le moment la prod contient [https://github.com/assomaker/manifmaker/blob/master/app/server/service/Inject24h43emeDataServerService.js](https://github.com/assomaker/manifmaker/blob/master/app/server/service/Inject24h43emeDataServerService.js). 

Le backlog est sur ce présent repo, install [https://www.zenhub.com/](https://www.zenhub.com/) pour avoir la vue pipelines. 
Il y a un GDoc egalement avec les specs en francais et des comments qui pointent vers les issues. Il est dans un shared folder 24h. 

En gros, pour etre IsoAssomaker il reste
* pass secu + export pdf
* improve agenda pdf export
* validate everything (ideally via automated tests)
* small refactoring on the timeslots
* polish user update form view

L'idée est de rapidement boucler IsoAssomaker pour bosser sur 1.0 (parce que bon, le but c'est de faire plus que l'existant, pas juste de refactor avec une techno récente). Connais tu d'autre devs intéressé par reprendre ce projet ?

**Comment by LeoMouyna** [comment]
@remipichon J'ai essayé sur Firefox, firefox dev edition et chromium sur mon PC perso et sur les 3 le tour guidé ne marche pas. Je réessayerai sur Chrome au local (j'en veux pas sur ma machine 😛)

Ok j'ai repris l'extension zenhub, mais je vois 42 issues dans le backlog sans compter celles dans le sprint backlog ça me parait assez fat comme reste à faire. Du coup je ne sais pas qui pourrait être intéressé en plus mais dans tous les cas, il va falloir proposer des issues simples pour comprendre la philosophie du code (si il y a des principes un peu exotiques par exemple) pour ensuite bosser sur les plus grosses fonctionnalités.

Par contre je sais aussi que le BdE/CVA veulent mettre en place une équipe DSI multi-asso et que le sujet de manif maker pourrait en intéresser certains. Bref pour les détails je pense qu'il faut qu'on se cale un point pour en discuter.

**Comment by remipichon** [comment]
@LeoMouyna chelou que le tour ne fonctionne pas. Faudrait que je vois sur ton écran ce qu'il se passe. 

Le projet a été stoppé en plein dev mais il ne reste pas grand chose. L'ensemble du In Progress + Sprint + Backlog font 118 points alors que pres de 500 points sont déja à valider (j'ai pas tout de suite commencé avec les points, il y en a quelque chose comme 100-200 non comptabilisés). L'archi du projet est solide, le build/deploy est pret, non vraiment il ne reste pas grand chose pour finir IsoAssomaker. Il y a de la place pour le 1.0 et la ca deviendra interessant. 

Excellent pour le DSI multi-asso, peux tu entrer en contact avec le BdE/CVA et leur demander s'il y a des devs NodeJs et/ou Android ? (tu peux dire que le front c'est du comme du View/React). 

EDIT
J'ai trié et Sprint et Blacklog font 83 points.

**Comment by remipichon** [comment]
@LeoMouyna peux tu essayer le tour ? J'ai redémarré le bidule
