### ISSUE TITLE
ajouter autoform materialize and le customiser à souhait

### ISSUE THREAD

**Issue by remipichon** [assomaker/manifmaker#61]
https://atmospherejs.com/gildaspk/autoform-materialize

demo
http://autoform-materialize-playground.meteor.com/

Ne pas hesiter à regarder tous les autres templates

**Comment by PtiLuky** [comment]
Du coup ça sans materialize, ça saute non ?
Ou chercher équivalent

**Comment by remipichon** [comment]
Wep, plus besoin de cette issue
