### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by remipichon** [assomaker/manifmaker#9]
Installer Iron router 

Route pour anim : 
anim
anim/:groupId
anim/:groupId/:animId
anim/:groupId/:animId/edit

Route pour workflow anim

Route pour task :
idem anim pour le moment

Route pour affectation :
userToTask/:userId/:taskId/:timeslotid/assign 
userToTask/:userId/:taskId/:timeslotid/unassign 

taskUserTo/:taskId/:timeslotId/:userId/assign 
taskUserTo/:taskId/:timeslotId/:userId/unassign

**Comment by ghost** [comment]
Je comprends ton UserToTask mais pas le TaskUserToTask. Pourquoi ce n'est pas TaskToUser/TaskId/timeslotid/UserId/assign ?

**Comment by remipichon** [comment]
Bad copy paste :)

**Comment by ghost** [comment]
T'as vu je suis :p

2015-11-23 9:57 GMT+01:00 Remi Pichon notifications@github.com:

> Bad copy paste :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/assomaker/manifmaker/issues/9#issuecomment-158879663.

## 

_Constant Palliere_
5ème année école d'ingénieur
Génie Mécanique Conception

_constant.palliere@ constant.palliere@gmail.cominsa-lyon.fr
http://insa-lyon.fr/_
06 82 82 41 26
